// react/my_songs/frontend/src/Components/Layout/Menu/Menu.tsx
import { NavLink } from "react-router-dom";
import "./Menu.css";
import { useEffect, useState } from "react";

function Menu(): JSX.Element {
  const [categories, setCategories] = useState([]);

  useEffect(() => {
    if (localStorage.getItem("Categories")) {
      //setCategories(JSON.parse(localStorage.getItem("Categories") as any));
    }
  }, []);

  return (
    <div className="Menu">
      <h2>Main Menu</h2>
      <hr />
      <NavLink to="/">All Songs</NavLink>
      <br />
      <br />
      <NavLink to="/addSong">Add Song</NavLink>
      <br />
      <br />
      <NavLink to="/addCategory">Add Category</NavLink>
      <br />
      <br />
      <NavLink to="/search">Song Search</NavLink>
      <br />
      <br />
      <NavLink to="/favorites">Favorites</NavLink>
      <br />
      <br />
      <NavLink to="/about">About Us</NavLink>
      <hr />
      {categories.map((item) => {
        return <h3>{item}</h3>;
      })}
    </div>
  );
}

export default Menu;

// angular/youtube/frontend/src/app/Layout/menu/menu.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.css'],
})
export class MenuComponent {
  constructor(private router: Router) {}

  nadavClick() {
    //console.log('nadav the ...');
    //this.router.navigate(['/player/U6XcNpYQ_zI']);
    this.router.navigate(['/player', 'U6XcNpYQ_zI']);
  }
}

<h2>Main Menu</h2>
<hr />
<h3>
  <a
    routerLink="/"
    [routerLinkActive]="['active']"
    [routerLinkActiveOptions]="{ exact: true }"
    >Home</a
  ><br /><br />
  <a routerLink="/list" [routerLinkActive]="['active']">all songs</a
  ><br /><br />
  <a routerLink="/addSong" [routerLinkActive]="['active']">add song</a
  ><br /><br />
  <a routerLink="/addCategory" [routerLinkActive]="['active']">add category</a
  ><br /><br />
  <a routerLink="/categories" [routerLinkActive]="['active']">all categories</a
  ><br /><br />
  <a routerLink="/about" [routerLinkActive]="['active']">about matan</a
  ><br /><br />
  <button (click)="nadavClick()">go nadav go</button>
</h3>
