// angular/youtube/src/app/Pages/player/player.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
@Component({
  selector: 'app-player',
  templateUrl: './player.component.html',
  styleUrls: ['./player.component.css'],
})
export class PlayerComponent implements OnInit {
  id: any = 'error';
  playerURL = 'https://www.youtube.com/embed/U6XcNpYQ_zI';

  constructor(private route: ActivatedRoute) {}

  ngOnInit(): void {
    this.id = this.route.snapshot.paramMap.get('id');
    console.log('https://youtu.be/' + this.id);
    //this.playerURL = 'https://www.youtube.com/embed/' + this.id;
  }
}

<p>player {{ id }}</p>
<hr />

<embed
  [src]="playerURL"
  wmode="transparent"
  type="video/mp4"
  width="100%"
  height="90%"
  allow="autoplay; encrypted-media; picture-in-picture"
  allowfullscreen
  title="Keyboard Cat"
/>

// react/my_songs/src/Components/Layout/Player/Player.tsx
import { useNavigate, useParams } from "react-router-dom";
import "./Player.css";
import { Button } from "@mui/material";

function Player(): JSX.Element {
  const params = useParams();
  const songID = params.videoId;
  const navigate = useNavigate();
  return (
    <div className="Player">
      <Button
        variant="outlined"
        color="secondary"
        onClick={() => navigate("/")}
      >
        Go Home
      </Button>
      <hr />
      <iframe
        width="560"
        height="315"
        src={`https://www.youtube.com/embed/${songID}?controls=0&autoplay=1`}
        title="YouTube video player"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
      ></iframe>
      <br />
      <hr />
      <br />
    </div>
  );
}

export default Player;
